import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('./SLINK_PDA_Dashboard.user.js', import.meta.url), 'utf8');
const preview = fs.readFileSync(new URL('./preview.html', import.meta.url), 'utf8');

assert.match(source, /@version\s+0\.2\.0/);
assert.match(source, /@grant\s+GM_xmlhttpRequest/);
assert.match(source, /@connect\s+api\.torn\.com/);
assert.doesNotMatch(source, /@require\b/);
assert.match(source, /viewport-fit=cover|safe-area-inset/);
assert.match(source, /grid-template-columns:minmax\(0,1fr\)/);
assert.match(source, /\.scroll\{min-width:0;min-height:0/);
assert.match(source, /\.launcher\[hidden\]\{display:none\}/);
assert.match(source, /launcher\.hidden = true/);
assert.match(source, /launcher\.hidden = false/);
assert.match(source, /orientation:landscape[\s\S]*position:absolute;top:50px;right:0/);
assert.match(source, /data-action="reset-layout"/);
assert.match(source, /orientationchange/);
assert.match(source, /MutationObserver/);
assert.match(source, /dashboardOpen = false/);
assert.match(source, /data-page="combat"/);
assert.match(source, /data-page="efficiency"/);
assert.match(source, /data-page="access"/);
assert.match(source, /data-combat-tab="leveling"/);
assert.match(source, /data-efficiency-tab="merits"/);
assert.match(source, /slinkcontributionworker\.richard-johnson554\.workers\.dev/);
assert.match(source, /slinkyleveling\.richard-johnson554\.workers\.dev/);
assert.match(source, /slinkwarworker\.richard-johnson554\.workers\.dev/);
assert.match(source, /slink\.level/);
assert.match(source, /slink\.war\.officer/);
assert.match(source, /slink\.adhd\.alerts/);
assert.match(source, /considious:torn-api-ledger:v1/);
assert.match(source, /data-module-root="leveling"/);
assert.match(source, /data-module-root="war"/);
assert.match(source, /data-module-root="stats"/);
assert.match(source, /data-module-root="alerts"/);
assert.match(source, /data-module-root="merits"/);
assert.match(source, /page\.php\?sid=attack&user2ID=/);
assert.doesNotMatch(source, /loader2?\.php/i);
assert.doesNotMatch(source, /location\.(?:reload|replace|assign)\s*\(/);
assert.doesNotMatch(source, /history\.(?:go|back|forward)\s*\(/);
assert.doesNotMatch(source, /chrome\.(?:runtime|storage|alarms)/);
assert.match(preview, /SLINK_PDA_Dashboard\.user\.js/);

console.log('SLINK PDA overlay static safety and recovery checks passed.');
